"""Evaluate a model: wikitext-2 perplexity + optional lm-evaluation-harness benchmarks."""
import argparse
import json
import math
import os
import sys
from pathlib import Path

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer


def compute_perplexity(
    model,
    tokenizer,
    dataset_name: str = "wikitext",
    dataset_config: str = "wikitext-2-raw-v1",
    split: str = "test",
    max_length: int = 2048,
    stride: int = 512,
) -> float:
    """Compute perplexity on wikitext-2 using sliding window."""
    from datasets import load_dataset

    ds = load_dataset(dataset_name, dataset_config, split=split)
    text = "\n\n".join(ds["text"])
    encodings = tokenizer(text, return_tensors="pt")
    input_ids = encodings.input_ids.to(model.device)

    nlls = []
    seq_len = input_ids.size(1)
    prev_end_loc = 0

    for begin_loc in range(0, seq_len, stride):
        end_loc = min(begin_loc + max_length, seq_len)
        trg_len = end_loc - prev_end_loc
        input_chunk = input_ids[:, begin_loc:end_loc]

        target_ids = input_chunk.clone()
        target_ids[:, :-trg_len] = -100

        with torch.no_grad():
            outputs = model(input_chunk, labels=target_ids)
            neg_log_likelihood = outputs.loss

        nlls.append(neg_log_likelihood.float().item())
        prev_end_loc = end_loc
        if end_loc == seq_len:
            break

    ppl = math.exp(sum(nlls) / len(nlls))
    return ppl


def run_lm_eval(model_path: str, tasks: list = None) -> dict:
    """Run lm-evaluation-harness benchmarks. Returns dict of task->metric."""
    if tasks is None:
        tasks = ["hellaswag", "arc_easy", "piqa"]

    try:
        import lm_eval
        from lm_eval.models.huggingface import HFLM

        model = HFLM(pretrained=model_path, batch_size=4)
        results = lm_eval.simple_evaluate(
            model=model,
            tasks=tasks,
            batch_size=4,
        )
        metrics = {}
        for task_name, task_result in results["results"].items():
            # Extract accuracy or acc_norm
            acc = task_result.get("acc_norm,none", task_result.get("acc,none", None))
            if acc is not None:
                metrics[task_name] = round(acc * 100, 1)
        return metrics
    except ImportError:
        print("WARNING: lm-evaluation-harness not installed. Skipping benchmarks.")
        print("  Install with: pip install lm-eval")
        return {}
    except Exception as e:
        print(f"WARNING: lm-eval failed: {e}")
        return {}


def measure_model_stats(model_path: str) -> dict:
    """Count parameters and measure disk size."""
    model = AutoModelForCausalLM.from_pretrained(model_path, torch_dtype=torch.float16)
    params = sum(p.numel() for p in model.parameters())

    total_size = 0
    for f in Path(model_path).rglob("*"):
        if f.is_file():
            total_size += f.stat().st_size

    return {
        "params": params,
        "disk_bytes": total_size,
        "disk_mb": round(total_size / 1e6, 1),
    }


def write_results_table(results: list, output_path: str):
    """Write results as a markdown table."""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    header = "| Model | Params | Disk (Q4) | PPL ↓ | HellaSwag | ARC-e | PIQA | tok/s | Peak RAM |"
    sep = "|-------|--------|-----------|-------|-----------|-------|------|-------|----------|"

    lines = ["# qunart Benchmark Results\n", "", header, sep]
    for r in results:
        line = "| {} | {} | {} | {} | {} | {} | {} | {} | {} |".format(
            r.get("model", "?"),
            f"{r.get('params', 0):,}" if r.get('params') else "?",
            r.get("disk_q4", "TBD"),
            f"{r.get('ppl', 0):.1f}" if r.get('ppl') else "TBD",
            r.get("hellaswag", "TBD"),
            r.get("arc_easy", "TBD"),
            r.get("piqa", "TBD"),
            r.get("tok_s", "TBD"),
            r.get("peak_ram", "TBD"),
        )
        lines.append(line)

    lines.append("")
    lines.append("*tok/s and Peak RAM measured on-device. TBD = not yet measured.*")
    lines.append("")
    lines.append(f"Generated by `scripts/evaluate.py`")

    with open(output_path, "w") as f:
        f.write("\n".join(lines))
    print(f"Results written to {output_path}")


def main():
    parser = argparse.ArgumentParser(description="Evaluate model perplexity and benchmarks")
    parser.add_argument("--model", required=True, help="HF model path or local directory")
    parser.add_argument("--label", default=None, help="Label for results table")
    parser.add_argument("--output", default="results/RESULTS.md", help="Output markdown file")
    parser.add_argument("--skip-lm-eval", action="store_true", help="Skip lm-evaluation-harness")
    parser.add_argument("--append", action="store_true", help="Append to existing results")
    parser.add_argument("--device", default="auto")
    args = parser.parse_args()

    label = args.label or args.model
    device = args.device
    if device == "auto":
        device = "cuda" if torch.cuda.is_available() else "cpu"

    print(f"Loading model: {args.model}")
    tokenizer = AutoTokenizer.from_pretrained(args.model)
    model = AutoModelForCausalLM.from_pretrained(
        args.model, torch_dtype=torch.float16, device_map=device
    )
    model.eval()

    # Params
    params = sum(p.numel() for p in model.parameters())
    print(f"Parameters: {params:,}")

    # Perplexity
    print("Computing wikitext-2 perplexity...")
    ppl = compute_perplexity(model, tokenizer)
    print(f"Perplexity: {ppl:.2f}")

    result = {
        "model": label,
        "params": params,
        "ppl": ppl,
    }

    # lm-eval benchmarks
    if not args.skip_lm_eval:
        print("Running lm-evaluation-harness benchmarks...")
        metrics = run_lm_eval(args.model)
        result.update(metrics)
    else:
        print("Skipping lm-eval benchmarks (--skip-lm-eval)")

    # Write results
    results = [result]
    write_results_table(results, args.output)
    print("Done.")


if __name__ == "__main__":
    main()
